### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by luislourenco** [mulian/smart-daemon-control#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [smart-daemon-control](https://github.com/mulian/smart-daemon-control) package, v0.7.2
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/luislourenco/.atom/packages/smart-daemon-control/lib/scan-deamons.coffee:15

TypeError: Cannot read property 'length' of undefined
  at /Users/luislourenco/.atom/packages/smart-daemon-control/lib/scan-deamons.coffee:15:9
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:277:18
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:192:18
  at FSReqWrap.oncomplete (fs.js:82:15)

```
### Commands

```
  7x -4:46.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:41.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -4:01.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:57.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 13x -3:51.1.0 click (button.btn.btn-info.icon.icon-cloud-download.install-button)
  3x -2:04.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:02.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  9x -1:56.9.0 click (button.btn.btn-info.icon.icon-cloud-download.install-button)
  5x -0:33.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:05.4.0 click (span.scan-button)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
aligner-php, v1.0.0
atom-autocomplete-php, v0.13.4
autocomplete-php, v0.3.7
cakephp-snippets, v0.6.1
cakephp3-snippets, v0.5.0
color-picker, v2.0.13
css-snippets, v0.9.0
data-atom, v0.11.0
doctrine, v0.3.0
drunken-php, v0.2.0
emmet-snippets-compatibility, v1.0.0
javascript-snippets, v1.0.0
language-javascript-jsx, v0.3.7
language-javascript-semantic, v0.2.1
language-sql-mysql, v0.3.1
language-tsql, v0.19.0
linter, v1.8.1
linter-php, v1.0.5
linter-phpcs, v1.1.4
linter-phplint, v0.1.0
linter-phpmd, v1.2.1
minimap, v4.13.4
php-analyser, v0.2.0
php-composer-completion, v0.3.4
php-cs-fixer, v2.5.0
php-debug, v0.1.3
php-extract-method, v0.1.1
php-getters-setters, v0.5.5
php-introspector, v1.0.0
phpunit, v1.1.1
pigments, v0.15.0
quick-docs, v0.1.0
robin-language-php, v0.9.0
smart-daemon-control, v0.7.2
standard-formatter, v1.1.3
travis-ci-status, v0.18.0
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by mulian** [comment]
It looks like you don't use brew?
If so there is no other scan algorithm right now for Mac OS. You need to add the deamons manually (README.md -> Add new Daemon).

What do you use? MacPorts?

**Comment by luislourenco** [comment]
Hi Max,

Thanks for your answer i gone see when i have time for now i’m just experimenting out but thanks anyway.

Luis
