### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by aitorllj93** [mulian/smart-daemon-control#2]
[Enter steps to reproduce below:]
1. Create new Item
   [⌘+⇧+P] and choose "Smart Daemon Controll: New Daemon"
2. ...

**Atom Version**: 1.0.19
**System**: Linux Mint
**Thrown From**: [smart-daemon-control](https://github.com/mulian/smart-daemon-control) package, v0.7.2
### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:772

TypeError: Cannot read property 'split' of undefined
  at Function.module.exports.Range.fromText (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/range.js:49:19)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:551:24)
  at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:536:26
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:767:18)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:21)
  at TextBuffer.module.exports.TextBuffer.setText (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:474:19)
  at TextEditor.module.exports.TextEditor.setText (/usr/share/atom/resources/app.asar/src/text-editor.js:720:26)
  at DaemonItemConfigureView.module.exports.DaemonItemConfigureView.bindTextEditorView (/home/allamas/.atom/packages/smart-daemon-control/lib/daemon-item-configure-view.coffee:107:24)
  at DaemonItemConfigureView.module.exports.DaemonItemConfigureView.load (/home/allamas/.atom/packages/smart-daemon-control/lib/daemon-item-configure-view.coffee:114:6)
  at DaemonManagement.module.exports.DaemonManagement.showItemConfig (/home/allamas/.atom/packages/smart-daemon-control/lib/daemon-management.coffee:70:30)
  at DaemonManagement.module.exports.DaemonManagement.newDaemon (/home/allamas/.atom/packages/smart-daemon-control/lib/daemon-management.coffee:76:6)
  at atom-workspace.subscriptions.add.atom.commands.add.smart-daemon-control:new-daemon (/home/allamas/.atom/packages/smart-daemon-control/lib/smart-daemon-control.coffee:28:66)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -2:55.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:55.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:55.6.0 application:open-your-stylesheet (atom-text-editor.editor)
     -2:51.7.0 core:copy (atom-text-editor.editor.is-focused)
     -2:49.4.0 core:paste (atom-text-editor.editor.is-focused)
     -2:47.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:18.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:42.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:41.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:41.2.0 settings-view:view-installed-packages (atom-text-editor.editor)
     -0:09.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-material-monokai-syntax.theme-atom-material-ui)
     -0:07.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.5.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-material-monokai-syntax.theme-atom-material-ui)
     -0:02.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.0 smart-daemon-control:new-daemon (atom-workspace.workspace.scrollbars-visible-always.theme-material-monokai-syntax.theme-atom-material-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "material-monokai-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tab-control",
      "wrap-guide"
    ]
  },
  "smart-daemon-control": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.8
angularjs, v0.3.3
atom-material-ui, v0.6.2
audio, v1.5.0
autocomplete-modules, v1.3.0
autocomplete-paths, v1.0.2
bottom-dock, v0.3.5
clipboard-plus, v0.5.1
color-picker, v2.0.13
file-icon-supplement, v0.8.3
file-icons, v1.6.10
foldername-tabs, v0.1.5
grunt-manager, v0.1.9
gulp-manager, v0.2.10
keyboard-sounds, v0.2.0
language-ini, v1.12.0
linter, v1.8.1
linter-eslint, v3.1.1
material-monokai-syntax, v0.1.1
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.1
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
multi-wrap-guide, v0.22.3
pigments, v0.17.1
smart-daemon-control, v0.7.2
tabulation-control, v1.0.6
terminal-plus, v0.8.2

# Dev
No dev packages
```

**Comment by mulian** [comment]
Is it fixed with the new version (0.8.0)?

**Comment by aitorllj93** [comment]
Hi! Thanks for your time
I can't check that due to #3 issue :persevere:

**Comment by mulian** [comment]
try it again with Version 0.8.1 ;)

**Comment by aitorllj93** [comment]
Hi again! 

Now I get this, when creating new Item
1. Create new Item [⌘+⇧+P] and choose "Smart Daemon Controll: New Daemon"
2. ...

**Atom Version**: 1.1.0
**System**: Linux Mint
**Thrown From**: [smart-daemon-control](https://github.com/mulian/smart-daemon-control) package, v0.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'new' of undefined

```
At /home/allamas/.atom/packages/smart-daemon-control/lib/smart-daemon-control.coffee:62

TypeError: Cannot read property 'new' of undefined
    at atom-workspace.subscriptions.add.atom.commands.add.smart-daemon-control:new-daemon (/home/allamas/.atom/packages/smart-daemon-control/lib/smart-daemon-control.coffee:62:67)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:243:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:243:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
    at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:20)
```

### Commands

```
     -0:06.2.0 command-palette:toggle (div.panels-item)
  4x -0:03.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.6.0 smart-daemon-control:new-daemon (div.panels-item)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "material-monokai-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tab-control",
      "wrap-guide"
    ]
  },
  "smart-daemon-control": {}
}
```

### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.10
angularjs, v0.3.3
atom-material-ui, v0.6.4
audio, v1.5.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
bottom-dock, v0.3.5
clipboard-plus, v0.5.1
color-picker, v2.0.13
commentcode, v0.1.0
compare-files, v0.6.2
file-icon-supplement, v0.8.3
file-icons, v1.6.11
foldername-tabs, v0.1.5
grunt-manager, v0.1.11
gulp-manager, v0.2.13
keyboard-sounds, v0.2.0
language-htaccess, v0.1.1
language-ini, v1.14.0
linter, v1.10.0
linter-eslint, v4.0.0
material-monokai-syntax, v0.1.1
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
multi-wrap-guide, v0.23.0
pigments, v0.18.1
smart-daemon-control, v0.8.1
symbols-tree-view, v0.10.1
tabulation-control, v1.0.6
terminal-plus, v0.13.0
tree-ignore, v0.2.6

# Dev
No dev packages
```

**Comment by mulian** [comment]
Okay, now the second issue should be fixed (v0.8.2).
Sorry for this, next time i'll test with a clean atom installation.

**Comment by aitorllj93** [comment]
NP ;)

Now I get this error when launching Atom :S 
1. Open Atom with installed package
2. ...

**Atom Version**: 1.1.0
**System**: Linux Mint
**Thrown From**: [smart-daemon-control](https://github.com/mulian/smart-daemon-control) package, v0.8.2

### Stack Trace

Failed to activate the smart-daemon-control package

```
At Cannot read property 'items' of undefined

TypeError: Cannot read property 'items' of undefined
    at new DaemonItemCollection (/home/allamas/.atom/packages/smart-daemon-control/lib/daemon-item-collection.coffee:20:7)
    at Object.module.exports.SmartDaemonControl.activate (/home/allamas/.atom/packages/smart-daemon-control/lib/smart-daemon-control.coffee:42:35)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:232:19)
    at /usr/share/atom/resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:153:15)
    at /usr/share/atom/resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:474:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:457:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:300:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:452:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:436:46)
    at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:625:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:428:26)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "material-monokai-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tab-control",
      "wrap-guide"
    ]
  },
  "smart-daemon-control": {}
}
```

### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.10
atom-material-ui, v0.6.4
audio, v1.5.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
bottom-dock, v0.3.5
clipboard-plus, v0.5.1
color-picker, v2.0.13
commentcode, v0.1.0
compare-files, v0.6.2
file-icon-supplement, v0.8.3
file-icons, v1.6.11
foldername-tabs, v0.1.5
grunt-manager, v0.1.11
gulp-manager, v0.2.13
keyboard-sounds, v0.2.0
linter, v1.10.0
linter-eslint, v4.0.0
material-monokai-syntax, v0.1.1
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
multi-wrap-guide, v0.23.0
pigments, v0.18.1
smart-daemon-control, v0.8.2
symbols-tree-view, v0.10.1
tabulation-control, v1.0.6
terminal-plus, v0.13.0
tree-ignore, v0.2.6

# Dev
No dev packages
```

**Comment by mulian** [comment]
Okay, please try it again with v0.8.3. :)

**Comment by aitorllj93** [comment]
Hi! Thanks for all :)

That worked :+1:

**Comment by mulian** [comment]
NP
