### ISSUE TITLE
Failed to load the smart-daemon-control package

### ISSUE THREAD

**Issue by aitorllj93** [mulian/smart-daemon-control#3]
[Enter steps to reproduce below:]
1. Open Atom with smart-daemon-control installed
2. ...

**Atom Version**: 1.1.0
**System**: Linux Mint
**Thrown From**: [smart-daemon-control](https://github.com/mulian/smart-daemon-control) package, v0.8.0
**User**: root
### Stack Trace

Failed to load the smart-daemon-control package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/allamas/.atom/packages/smart-daemon-control/lib/views/check-list-view.coffee:2:5)
    at Object.<anonymous> (/home/allamas/.atom/packages/smart-daemon-control/lib/views/check-list-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/allamas/.atom/packages/smart-daemon-control/lib/daemon-add-wizard.coffee:3:17)
    at Object.<anonymous> (/home/allamas/.atom/packages/smart-daemon-control/lib/daemon-add-wizard.coffee:1:1)
    at Module._compile (module.js:428:26)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "material-monokai-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tab-control",
      "wrap-guide"
    ]
  },
  "smart-daemon-control": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.10
atom-material-ui, v0.6.4
audio, v1.5.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
bottom-dock, v0.3.5
clipboard-plus, v0.5.1
color-picker, v2.0.13
commentcode, v0.1.0
compare-files, v0.6.2
file-icon-supplement, v0.8.3
file-icons, v1.6.11
foldername-tabs, v0.1.5
grunt-manager, v0.1.11
gulp-manager, v0.2.13
keyboard-sounds, v0.2.0
linter, v1.10.0
linter-eslint, v4.0.0
material-monokai-syntax, v0.1.1
minimap, v4.16.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
multi-wrap-guide, v0.23.0
pigments, v0.18.1
smart-daemon-control, v0.8.0
symbols-tree-view, v0.10.1
tabulation-control, v1.0.6
terminal-plus, v0.13.0
tree-ignore, v0.2.6

# Dev
No dev packages
```

**Comment by mulian** [comment]
Thanks!
This bug is fixed now (v0.8.1).
